name: test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
    abc:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: print trash
          run: echo "hello world"

        - name: installing c++/c compiler
          run: sudo apt install build-essential

        - name: build-project
          run: mkdir build && cd build && cmake --build .. && make && ls -la
