name: test

on:
  push:
    branches: [ dev, main ]
  pull_request:
    branches: [ main ]

jobs:
    abc:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2

        - name: print trash
        - run: echo "hello world"
